Options_ = Dict(
"method"=>"SLP",
"algorithm"=>"Line Search",
"max_iter"=>3000,
"max_iter_inner"=>2000,
"LP_solver"=>GLPK.Optimizer,
"time_limit"=>Inf,
"epsilon"=>1e-6,
"eta"=>0.0,
"tau"=>0.8,
"rho"=>0.8,
"mu"=>1000.0,
"alpha_lb"=>1e-8);
